String str = "Java";
str = str.concat("Welcome");
System.out.println(str);
String str = "Java";
char character = str.charAt(1);
System.out.println(character);
String str = "Java";
int index = str.indexOf('a');
System.out.println(index);
String str = "Java";
int index = str.indexOf('a', str.indexOf('a') + 1);
System.out.println(index);
String str1 = "Java";
String str2 = "JAVA";
boolean result = str1.equals(str2);
System.out.println(result);
String str1 = "Java";
String str2 = "JAVA";
boolean result = str1.equalsIgnoreCase(str2);
System.out.println(result);
String str = "Java";
int index = str.lastIndexOf('a');
System.out.println(index);
